---
title: "Experiences"
format: html
editor: visual
---

## Research Affiliate

*May 2024 - Present*\
School of Medical Sciences\
Faculty of Science and Medicine\
University of Sydney\
New South Wales, Australia

## Part-time Teaching

*February 2024 - Present*\
School of Chemistry and Molecular Bioscience\
Faculty of Science, Medicine and Health\
University of Wollongong\
New South Wales, Australia

## Guest Scientist

*November 2023 - Present*\
[Knauer-Arloth Lab](https://www.psych.mpg.de/2664393/medizinische-genomforschung)\
Department Genes and Environment\
Max Planck Institute of Psychiatry\
Munich, Germany

## Scientific Officer (on deputation)

*October 2021 - Present*\
Molecular Biotechnology Division\
National Institute of Biotechnology\
Dhaka, Bangladesh

## Part-time Faculty

*February 2021 - September 2021*\
Department of Mathematics and Natural Sciences\
BRAC University\
Dhaka, Bangladesh

## Research Assistant

*August 2020 - September 2021*\
Department of Genetic Engineering and Biotechnology\
Faculty of Biological Science\
University of Dhaka\
Dhaka, Bangladesh\
Supervisor: [Professor Abu Ashfaqur Sajib](https://www.du.ac.bd/faculty/faculty_details/GET/1622)

## Research Intern

*December 2019*\
Genomics Facility\
Monash University Malaysia\
Selangor Darul Ehsan, Malaysia\
Contact Person: Professor Sadequr Rahman
