---
title: "Skill Set"
format: html
editor: visual
---

## Bioinformatics

-   Genome assembly and annotation
-   Functional genomics
-   Network analysis
-   Unimodal and multimodal (single-cell and bulk) data analyses

## Programming Languages

-   R
-   Python
-   C

## Statistics

-   Linear and non-linear models (multiple linear regression, generalized linear models, nonlinear regression)
-   Hypothesis testing (t-test, Wilcoxon rank-sum test, ANOVA, ANCOVA)
-   Dimensionality reductions (PCA, PLS-DA, UMAP, t-SNE)

## Machine Learning

-   Supervised (classification and regression)

-   Unsupervised (clustering, dimensionality reductions)

-   Self-supervised (contrastive and noncontrastive)

## Wet-lab Techniques

### Molecular biology

-   PCR
-   qPCR
-   Western blotting
-   Genetic transformation
-   Sanger sequencing
-   Next generation sequencing (NextSeq 2000)
-   Flow cytometry

### Microbiology

-   Bacterial culture
-   Microscopy
-   Pathogen identification

### Biotechnology

-   Fermentation
-   Plant tissue culture
-   Testing bioactive propeties of compopunds in animal models
